/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardDebateIndexRouteImport } from './routes/dashboard/debate/index'
import { Route as DashboardAdsIndexRouteImport } from './routes/dashboard/ads/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardDebateNewRouteImport } from './routes/dashboard/debate/new'
import { Route as DashboardDebatePostIdRouteImport } from './routes/dashboard/debate/$postId'
import { Route as DashboardAdsNewRouteImport } from './routes/dashboard/ads/new'
import { Route as DashboardAdsAdIdRouteImport } from './routes/dashboard/ads/$adId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateIndexRoute = DashboardDebateIndexRouteImport.update({
  id: '/debate/',
  path: '/debate/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsIndexRoute = DashboardAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateNewRoute = DashboardDebateNewRouteImport.update({
  id: '/debate/new',
  path: '/debate/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebatePostIdRoute = DashboardDebatePostIdRouteImport.update({
  id: '/debate/$postId',
  path: '/debate/$postId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsNewRoute = DashboardAdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsAdIdRoute = DashboardAdsAdIdRouteImport.update({
  id: '/ads/$adId',
  path: '/ads/$adId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ads/$adId': typeof DashboardAdsAdIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/debate/$postId': typeof DashboardDebatePostIdRoute
  '/dashboard/debate/new': typeof DashboardDebateNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/ads/': typeof DashboardAdsIndexRoute
  '/dashboard/debate/': typeof DashboardDebateIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ads/$adId': typeof DashboardAdsAdIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/debate/$postId': typeof DashboardDebatePostIdRoute
  '/dashboard/debate/new': typeof DashboardDebateNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/ads': typeof DashboardAdsIndexRoute
  '/dashboard/debate': typeof DashboardDebateIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ads/$adId': typeof DashboardAdsAdIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/debate/$postId': typeof DashboardDebatePostIdRoute
  '/dashboard/debate/new': typeof DashboardDebateNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/ads/': typeof DashboardAdsIndexRoute
  '/dashboard/debate/': typeof DashboardDebateIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/ads/$adId'
    | '/dashboard/ads/new'
    | '/dashboard/debate/$postId'
    | '/dashboard/debate/new'
    | '/dashboard/users/$userId'
    | '/dashboard/ads/'
    | '/dashboard/debate/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/ads/$adId'
    | '/dashboard/ads/new'
    | '/dashboard/debate/$postId'
    | '/dashboard/debate/new'
    | '/dashboard/users/$userId'
    | '/dashboard/ads'
    | '/dashboard/debate'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/ads/$adId'
    | '/dashboard/ads/new'
    | '/dashboard/debate/$postId'
    | '/dashboard/debate/new'
    | '/dashboard/users/$userId'
    | '/dashboard/ads/'
    | '/dashboard/debate/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/': {
      id: '/dashboard/debate/'
      path: '/debate'
      fullPath: '/dashboard/debate/'
      preLoaderRoute: typeof DashboardDebateIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads/': {
      id: '/dashboard/ads/'
      path: '/ads'
      fullPath: '/dashboard/ads/'
      preLoaderRoute: typeof DashboardAdsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/new': {
      id: '/dashboard/debate/new'
      path: '/debate/new'
      fullPath: '/dashboard/debate/new'
      preLoaderRoute: typeof DashboardDebateNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/$postId': {
      id: '/dashboard/debate/$postId'
      path: '/debate/$postId'
      fullPath: '/dashboard/debate/$postId'
      preLoaderRoute: typeof DashboardDebatePostIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads/new': {
      id: '/dashboard/ads/new'
      path: '/ads/new'
      fullPath: '/dashboard/ads/new'
      preLoaderRoute: typeof DashboardAdsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads/$adId': {
      id: '/dashboard/ads/$adId'
      path: '/ads/$adId'
      fullPath: '/dashboard/ads/$adId'
      preLoaderRoute: typeof DashboardAdsAdIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdsAdIdRoute: typeof DashboardAdsAdIdRoute
  DashboardAdsNewRoute: typeof DashboardAdsNewRoute
  DashboardDebatePostIdRoute: typeof DashboardDebatePostIdRoute
  DashboardDebateNewRoute: typeof DashboardDebateNewRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardAdsIndexRoute: typeof DashboardAdsIndexRoute
  DashboardDebateIndexRoute: typeof DashboardDebateIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdsAdIdRoute: DashboardAdsAdIdRoute,
  DashboardAdsNewRoute: DashboardAdsNewRoute,
  DashboardDebatePostIdRoute: DashboardDebatePostIdRoute,
  DashboardDebateNewRoute: DashboardDebateNewRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardAdsIndexRoute: DashboardAdsIndexRoute,
  DashboardDebateIndexRoute: DashboardDebateIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
