/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdsIndexRouteImport } from './routes/dashboard/ads/index'
import { Route as DashboardAdsNewRouteImport } from './routes/dashboard/ads/new'
import { Route as DashboardAdsAdIdRouteImport } from './routes/dashboard/ads/$adId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsIndexRoute = DashboardAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsNewRoute = DashboardAdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsAdIdRoute = DashboardAdsAdIdRouteImport.update({
  id: '/ads/$adId',
  path: '/ads/$adId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ads/$adId': typeof DashboardAdsAdIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/ads/': typeof DashboardAdsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ads/$adId': typeof DashboardAdsAdIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/ads': typeof DashboardAdsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ads/$adId': typeof DashboardAdsAdIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/ads/': typeof DashboardAdsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/ads/$adId'
    | '/dashboard/ads/new'
    | '/dashboard/ads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/ads/$adId'
    | '/dashboard/ads/new'
    | '/dashboard/ads'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/ads/$adId'
    | '/dashboard/ads/new'
    | '/dashboard/ads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads/': {
      id: '/dashboard/ads/'
      path: '/ads'
      fullPath: '/dashboard/ads/'
      preLoaderRoute: typeof DashboardAdsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads/new': {
      id: '/dashboard/ads/new'
      path: '/ads/new'
      fullPath: '/dashboard/ads/new'
      preLoaderRoute: typeof DashboardAdsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads/$adId': {
      id: '/dashboard/ads/$adId'
      path: '/ads/$adId'
      fullPath: '/dashboard/ads/$adId'
      preLoaderRoute: typeof DashboardAdsAdIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdsAdIdRoute: typeof DashboardAdsAdIdRoute
  DashboardAdsNewRoute: typeof DashboardAdsNewRoute
  DashboardAdsIndexRoute: typeof DashboardAdsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdsAdIdRoute: DashboardAdsAdIdRoute,
  DashboardAdsNewRoute: DashboardAdsNewRoute,
  DashboardAdsIndexRoute: DashboardAdsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
