/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardDebateIndexRouteImport } from './routes/dashboard/debate/index'
import { Route as DashboardCampaignsIndexRouteImport } from './routes/dashboard/campaigns/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardDebateNewRouteImport } from './routes/dashboard/debate/new'
import { Route as DashboardDebateCommentsRouteImport } from './routes/dashboard/debate/comments'
import { Route as DashboardDebatePostIdRouteImport } from './routes/dashboard/debate/$postId'
import { Route as DashboardCampaignsNewRouteImport } from './routes/dashboard/campaigns/new'
import { Route as DashboardCampaignsAdIdRouteImport } from './routes/dashboard/campaigns/$adId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateIndexRoute = DashboardDebateIndexRouteImport.update({
  id: '/debate/',
  path: '/debate/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateNewRoute = DashboardDebateNewRouteImport.update({
  id: '/debate/new',
  path: '/debate/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateCommentsRoute = DashboardDebateCommentsRouteImport.update({
  id: '/debate/comments',
  path: '/debate/comments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebatePostIdRoute = DashboardDebatePostIdRouteImport.update({
  id: '/debate/$postId',
  path: '/debate/$postId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsNewRoute = DashboardCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsAdIdRoute = DashboardCampaignsAdIdRouteImport.update({
  id: '/campaigns/$adId',
  path: '/campaigns/$adId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/$adId': typeof DashboardCampaignsAdIdRoute
  '/dashboard/campaigns/new': typeof DashboardCampaignsNewRoute
  '/dashboard/debate/$postId': typeof DashboardDebatePostIdRoute
  '/dashboard/debate/comments': typeof DashboardDebateCommentsRoute
  '/dashboard/debate/new': typeof DashboardDebateNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/debate/': typeof DashboardDebateIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campaigns/$adId': typeof DashboardCampaignsAdIdRoute
  '/dashboard/campaigns/new': typeof DashboardCampaignsNewRoute
  '/dashboard/debate/$postId': typeof DashboardDebatePostIdRoute
  '/dashboard/debate/comments': typeof DashboardDebateCommentsRoute
  '/dashboard/debate/new': typeof DashboardDebateNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/debate': typeof DashboardDebateIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/$adId': typeof DashboardCampaignsAdIdRoute
  '/dashboard/campaigns/new': typeof DashboardCampaignsNewRoute
  '/dashboard/debate/$postId': typeof DashboardDebatePostIdRoute
  '/dashboard/debate/comments': typeof DashboardDebateCommentsRoute
  '/dashboard/debate/new': typeof DashboardDebateNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/debate/': typeof DashboardDebateIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/campaigns/$adId'
    | '/dashboard/campaigns/new'
    | '/dashboard/debate/$postId'
    | '/dashboard/debate/comments'
    | '/dashboard/debate/new'
    | '/dashboard/users/$userId'
    | '/dashboard/campaigns/'
    | '/dashboard/debate/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/campaigns/$adId'
    | '/dashboard/campaigns/new'
    | '/dashboard/debate/$postId'
    | '/dashboard/debate/comments'
    | '/dashboard/debate/new'
    | '/dashboard/users/$userId'
    | '/dashboard/campaigns'
    | '/dashboard/debate'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/campaigns/$adId'
    | '/dashboard/campaigns/new'
    | '/dashboard/debate/$postId'
    | '/dashboard/debate/comments'
    | '/dashboard/debate/new'
    | '/dashboard/users/$userId'
    | '/dashboard/campaigns/'
    | '/dashboard/debate/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/': {
      id: '/dashboard/debate/'
      path: '/debate'
      fullPath: '/dashboard/debate/'
      preLoaderRoute: typeof DashboardDebateIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/': {
      id: '/dashboard/campaigns/'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/new': {
      id: '/dashboard/debate/new'
      path: '/debate/new'
      fullPath: '/dashboard/debate/new'
      preLoaderRoute: typeof DashboardDebateNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/comments': {
      id: '/dashboard/debate/comments'
      path: '/debate/comments'
      fullPath: '/dashboard/debate/comments'
      preLoaderRoute: typeof DashboardDebateCommentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debate/$postId': {
      id: '/dashboard/debate/$postId'
      path: '/debate/$postId'
      fullPath: '/dashboard/debate/$postId'
      preLoaderRoute: typeof DashboardDebatePostIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/new': {
      id: '/dashboard/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/dashboard/campaigns/new'
      preLoaderRoute: typeof DashboardCampaignsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/$adId': {
      id: '/dashboard/campaigns/$adId'
      path: '/campaigns/$adId'
      fullPath: '/dashboard/campaigns/$adId'
      preLoaderRoute: typeof DashboardCampaignsAdIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCampaignsAdIdRoute: typeof DashboardCampaignsAdIdRoute
  DashboardCampaignsNewRoute: typeof DashboardCampaignsNewRoute
  DashboardDebatePostIdRoute: typeof DashboardDebatePostIdRoute
  DashboardDebateCommentsRoute: typeof DashboardDebateCommentsRoute
  DashboardDebateNewRoute: typeof DashboardDebateNewRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute
  DashboardDebateIndexRoute: typeof DashboardDebateIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCampaignsAdIdRoute: DashboardCampaignsAdIdRoute,
  DashboardCampaignsNewRoute: DashboardCampaignsNewRoute,
  DashboardDebatePostIdRoute: DashboardDebatePostIdRoute,
  DashboardDebateCommentsRoute: DashboardDebateCommentsRoute,
  DashboardDebateNewRoute: DashboardDebateNewRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
  DashboardDebateIndexRoute: DashboardDebateIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
